version: '3.8'

services:
  mototec-prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: mototec-pm-prod
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
